routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

use App\Item;
use App\ItemType;
use App\Subject;
use App\Models\Node;


Route::get('/', function (Request $request) {
    return view('frontend_layouts.main', [
        'search_result' => [],
        'items' => Item::where('published', 1)->orderByDesc('document_date')->paginate(20),
        // 'items' => Item::published()->orderByDesc('document_date')->published()->paginate(20),
        'categories' => ItemType::all(),
        'subjects' => Subject::all(),
        'c' => $request['c'] ? $request['c'] : 0,
        's' => $request['s'] ? $request['s'] : 0,
        'q' => $request['q'] ? $request['q'] : ""
    ]);
})->name('home');

Route::get('/search', function (Request $request) {
    Log::Info($request);

    //$validator = Validator::make($request->all(), [
        //'c' => 'required|integer|min:1|exists:item_types,id',
        //'s' => 'required|integer|min:1|exists:subjects,id',
        //'q' => 'sometimes|string',
    //]);

    $validatorQ = Validator::make($request->all(), [
        'q' => 'required|string'
    ]);

    $validatorC = Validator::make($request->all(), [
        'c' => 'required|integer|min:1|exists:item_types,id'
    ]);

    $validatorS = Validator::make($request->all(), [
        's' => 'required|integer|min:1|exists:subjects,id'
    ]);

    $search_result = [];

    if($validatorQ->fails() && $validatorC->fails() && $validatorS->fails()) {
        $search_result = Item::published();
    } else {
        if(!$validatorC->fails()) {
            $search_result = $search_result ? $search_result->category($request['c']) : Item::category($request['c']);
        }

        if(!$validatorS->fails()) {
            $search_result = $search_result ? $search_result->findSubject($request['s']) : Item::findSubject($request['s']);
        }

        if(!$validatorQ->fails()) {
            $search_result = $search_result ? $search_result->title($request['q']) : Item::title($request['q']);
        }
    }

    return view('frontend_layouts.search', [
        'search_result' => $search_result ? $search_result->paginate(12)->appends($request->except('page')) : $search_result,
        'items' => Item::orderByDesc('document_date')->limit(4)->get(),
        'categories' => ItemType::all(),
        'subjects' => Subject::all(),
        'c' => $request['c'] ? $request['c'] : 0,
        's' => $request['s'] ? $request['s'] : 0,
        'q' => $request['q'] ? $request['q'] : ""
    ]);
})->name('search');


Route::get('/book-details/{id}', function ($id) {
    // $item = Item::published()->findOrFail($id);
    // if(Auth::check() && $item->uploaded_by->id == Auth::user()->id) {
    //     // do nothing, just continue
    // } else if($item->visibility && $item->visibility->type > 1) {
    //     if(Auth::check()) {
    //         Log::info(Auth::check());
    //         Log::info($item->visibility->users);
    //         if($item->visibility->type == 3) {
    //             Log::info('type 3');
    //             $user = $item->visibility->users()->where('user_id', Auth::user()->id)->get();
    //             Log::info($user);
    //             Log::info($user->count());
    //             if($user->count() >= 1) {
    //                 Log::info('abort');
    //                 return abort(403, "You are not allowed to access this document");
    //             }
    //         }

    //         if($item->visibility->type == 4) {
    //             Log::info('type 4');
    //             $item->visibility->users()->where('user_id', Auth::user()->id)->firstOrFail();
    //         }
    //     } else {
    //         return redirect()->route('login', ['next' => URL::to('/book-details/'.$id)]);
    //     }
    // }

    $item = Item::with("visibility.users")->findOrFail($id);
    if($item->visibility->type != 1 && $item->visibility->type != 2) {
        if(Auth::check()) {
            if($item->visibility->type == 4) {
                $allowed_ids = array_map(function($user){
                    return $user["id"];
                }, $item->visibility->users->toArray());
                if(!in_array(auth()->user()->id, $allowed_ids) && $item->user_id != auth()->user()->id) {
                    return abort(403, "Sorry ".auth()->user()->first_name.", you are not allowed to access this document.");
                }
            }
        } else {
            return redirect()->route("login", ["next" => URL::to("/book-details/".$id)]);
        }
    } elseif($item->visibility->type == 2) {
        if(!Auth::check())
            return redirect()->route("login", ["next" => URL::to("/book-details/".$id)]);
    }

    return view('frontend_layouts.book_details', [
        'item' => $item,
        'items' => Item::published()->paginate(8),
        'related_items' => Item::relatedItem($item) ? Item::relatedItem($item)->paginate(2) : Item::relatedItem($item)
    ]);
})->name('book_details');

Auth::routes();

Route::get('current_user', ['uses'=> 'ItemsController@current_user']);
Route::get('profile_photo/{id}', ['uses' => 'UsersController@show_profile']);
Route::get('items/{total}/{offset}', ['uses'=> 'ItemFilesController@get_items']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('users/{id}/delete', 'UsersController@delete')->name('users.delete');
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('items', 'ItemsController', ['only' => ['index', 'show', 'edit', 'create']]);
    Route::get('countries/{id}/delete', 'CountriesController@delete')->name('countries.delete');
    Route::resource('countries', 'CountriesController');

    Route::get('categories/{id}/delete', 'ItemTypesController@delete')->name('categories.delete');
    Route::resource('categories', 'ItemTypesController');

    Route::get('authors/{id}/delete', 'AuthorsController@delete')->name('authors.delete');
    Route::resource('authors', 'AuthorsController');

    Route::get('subject/{id}/delete', 'SubjectsController@delete')->name('subjects.delete');
    Route::resource('subjects', 'SubjectsController');

    Route::get('profile', 'ProfileController@edit')->name('profile');
    Route::post('profile', 'ProfileController@update')->name('profile');
    Route::get('setting', 'SettingController@edit')->name('setting');
    Route::post('setting', 'SettingController@update')->name('setting');
    Route::get('notifications', 'NotificationController@index')->name('notifications');
    Route::get('trash', 'TrashController@index')->name('trash');
});

Route::redirect('/admin', '/admin/dashboard', 301);

app/Models/User.php
<?php

/**
 * Created by Reliese Model.
 * Date: Sun, 14 Jan 2018 21:07:40 +0700.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class User
 * 
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property int $role_id
 * @property string $biography
 * 
 * @property \App\Models\Role $role
 * @property \Illuminate\Database\Eloquent\Collection $items
 * @property \Illuminate\Database\Eloquent\Collection $user_photos
 * @property \Illuminate\Database\Eloquent\Collection $visibilities
 *
 * @package App\Models
 */
class User extends Eloquent
{
	protected $casts = [
		'role_id' => 'int'
	];

	protected $hidden = [
		'password',
		'remember_token'
	];

	protected $fillable = [
		'first_name',
		'last_name',
		'email',
		'password',
		'remember_token',
		'role_id',
		'biography'
	];

	public function role()
	{
		return $this->belongsTo(\App\Models\Role::class);
	}

	public function items()
	{
		return $this->hasMany(\App\Models\Item::class);
	}

	public function user_photos()
	{
		return $this->hasMany(\App\Models\UserPhoto::class);
	}

	public function visibilities()
	{
		return $this->belongsToMany(\App\Models\Visibility::class, 'visibility_users')
					->withPivot('id')
					->withTimestamps();
	}
}

app/User.php
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'biography'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function items()
    {
        return $this->hasMany('App\Item', 'user_id', 'id');
    }

    public function full_name()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function is_role($role_name)
    {
        return $this->role->name == $role_name;
    }

    public function photo()
    {
        return $this->hasOne('App\UserPhoto', 'user_id', 'id');
    }

    public function isAdmin()
    {
        return $this->role->isAdmin();
    }

    public function isRoot()
    {
        return $this->role->isRoot();
    }

    public function delete()
    {
        $user_target = User::find(1);
        foreach($this->items as $item)
        {
           $item->uploaded_by()->associate($user_target);
           $item->save();
        }

        return parent::delete();
    }
}

app/Http/Controllers/API/UsersController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;

use App\User;
use App\Role;
use App\Http\Resources\Users as UsersResource;

class UsersController extends Controller
{
    public function index()
    {
        return UsersResource::collection(User::all());
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

use App\User;
use App\Role;
use App\UserPhoto;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('role', ['except' => ['index']]);
    }

    public function index()
    {
        return view('users.index', [
            'users' => User::all()
        ]);
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.view', ['user' => $user]);
    }

    public function create()
    {
        if(Auth::user()->is_role('contributor')) {
            return redirect()->route('dashboard');
        }

        return view('users.create', [
            'roles' => Role::all()
        ]);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
            'role_id' => 'required|integer|exists:roles,id'
        ]);

        if($validator->fails()) {
            return back()
                ->with('alert-danger', 'Form error!')
                ->withErrors($validator)
                ->withInput();
        }

        $role = Role::find($request['role_id']);

        $user = User::create([
            'first_name' => $request['first_name'],
            'last_name' => $request['last_name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
            'biography' => ''
        ]);

        $user->role()->associate($role);
        $user->save();

        return back()->with('alert-success', 'User created!');
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit', ['user' => $user, 'roles' => Role::all()]);
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => [
                'required', 'string', 'email', 'max:255',
                Rule::unique('users')->ignore($user->id)
            ],
            'password' => 'required|string|min:6|confirmed',
            'role_id' => 'required|integer|exists:roles,id'
        ]);

        if($validator->fails()) {
            return back()
                ->with('alert-danger', 'Form error!')
                ->withErrors($validator)
                ->withInput();
        }

        $role = Role::find($request['role_id']);

        $user->first_name = $request['first_name'];
        $user->last_name = $request['last_name'];
        $user->email = $request['email'];
        $user->password = bcrypt($request['password']);

        $user->role()->associate($role);
        $user->save();

        return back()->with('alert-success', 'User updated!');
    }


    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if($user->isRoot() || Auth::user()->id == $user->id)
            return abort(404);

        $user->delete();
        return redirect()->route('users.index');
    }

    public function delete($id)
    {
        $user = User::findOrFail($id);
        if($user->isRoot() || Auth::user()->id == $user->id)
            return abort(404);
        return view('users.delete', ['user' => $user]);
    }

    public function show_profile($id)
    {
      $photo = UserPhoto::where('user_id', $id)->get();
      // var_dump(sizeof($photo));
      if (sizeof($photo) < 1)
      {
        $array = [];
        // $t = new stdClass();
        // $t->download_path = "upload/qnphPujlGCECztQN9cOdsAR07xwZKOcgmsGNjTzB.png";
        // return $t;
        $array[0]['download_path'] = "upload/qnphPujlGCECztQN9cOdsAR07xwZKOcgmsGNjTzB.png";
        return $array;
      }

      return $photo;
    }

    public function test()
    {
      
    }
}

resources/views/users/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Create User</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('users.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" id="first_name" name="first_name" class="form-control"value="{{ old('first_name') }}">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" id="last_name" name="last_name" class="form-control" value="{{ old('last_name') }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" id="email" name="email" class="form-control" value="{{ old('email') }}">
                    </div>
                    <div class="form-group">
                        <label for="role">Role</label>
                        <select id="role_id" name="role_id" class="select form-control" value="{{ old('role_id') }}">
                            @foreach($roles as $role)
                                <option {{ $role->id == old('role_id') ? 'selected' : '' }} value="{{ $role->id }}">
                                {{ $role->complete_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password Confirmation</label>
                        <input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-md btn-primary pull-right">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/delete.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Delete User</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('users.destroy', [$user->id]) }}">
                    {{ csrf_field() }}
                    <input name="_method" type="hidden" value="DELETE">
                    <input name="id" type="hidden" value="{{$user->id}}">
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" id="first_name" name="first_name" class="form-control"value="{{ old('first_name', $user->first_name) }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" id="last_name" name="last_name" class="form-control" value="{{ old('last_name', $user->last_name) }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" id="email" name="email" class="form-control" value="{{ old('email', $user->email) }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="role">Role</label>
                        <input type="text" id="role" name="role" class="form-control" value="{{ old('email', $user->role->name) }}" readonly>
                    </div>
                    <a href="{{route('users.index')}}" class="btn btn-md btn-primary pull-left">CANCEL</a>
                    <button type="submit" class="btn btn-md btn-danger pull-right">DELETE</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Create User</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('users.update', [$user->id]) }}">
                    {{ csrf_field() }}
                    <input name="_method" type="hidden" value="PUT">
                    <div class="form-group">
                        <label for="first_name">First Name</label>
                        <input type="text" id="first_name" name="first_name" class="form-control"value="{{ old('first_name', $user->first_name) }}">
                    </div>
                    <div class="form-group">
                        <label for="last_name">Last Name</label>
                        <input type="text" id="last_name" name="last_name" class="form-control" value="{{ old('last_name', $user->last_name) }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" id="email" name="email" class="form-control" value="{{ old('email', $user->email) }}">
                    </div>
                    <div class="form-group">
                        <label for="role">Role</label>
                        <select id="role_id" name="role_id" class="select form-control" value="{{ old('role_id', $user->role->id) }}">
                            @foreach($roles as $role)
                            <option {{ $role->id == old('role_id', $user->role->id) ? 'selected' : '' }} value="{{ $role->id }}">
                                {{ $role->complete_name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="password">Password Confirmation</label>
                        <input type="password" id="password_confirmation" name="password_confirmation" class="form-control">
                    </div>

                    <button type="submit" class="btn btn-md btn-primary pull-right">SAVE</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">User List</div>

            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Joined at</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $user->first_name }}</td>
                            <td>{{ $user->last_name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->role->complete_name }}</td>
                            <td>{{ $user->created_at }}</td>
                            <td>
                                <a href="{{route('users.edit', [$user->id])}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                @if(!Auth::user()->isRoot() || Auth::user()->id != $user->id)
                                <a href="{{route('users.delete', [$user->id])}}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/view.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">View User Details</div>

            <div class="panel-body">
                {{ $user->first_name }} {{ $user->last_name }}
            </div>
        </div>
    </div>
</div>
@endsection