routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

use App\Item;
use App\ItemType;
use App\Subject;
use App\Models\Node;


Route::get('/', function (Request $request) {
    return view('frontend_layouts.main', [
        'search_result' => [],
        'items' => Item::where('published', 1)->orderByDesc('document_date')->paginate(20),
        // 'items' => Item::published()->orderByDesc('document_date')->published()->paginate(20),
        'categories' => ItemType::all(),
        'subjects' => Subject::all(),
        'c' => $request['c'] ? $request['c'] : 0,
        's' => $request['s'] ? $request['s'] : 0,
        'q' => $request['q'] ? $request['q'] : ""
    ]);
})->name('home');

Route::get('/search', function (Request $request) {
    Log::Info($request);

    //$validator = Validator::make($request->all(), [
        //'c' => 'required|integer|min:1|exists:item_types,id',
        //'s' => 'required|integer|min:1|exists:subjects,id',
        //'q' => 'sometimes|string',
    //]);

    $validatorQ = Validator::make($request->all(), [
        'q' => 'required|string'
    ]);

    $validatorC = Validator::make($request->all(), [
        'c' => 'required|integer|min:1|exists:item_types,id'
    ]);

    $validatorS = Validator::make($request->all(), [
        's' => 'required|integer|min:1|exists:subjects,id'
    ]);

    $search_result = [];

    if($validatorQ->fails() && $validatorC->fails() && $validatorS->fails()) {
        $search_result = Item::published();
    } else {
        if(!$validatorC->fails()) {
            $search_result = $search_result ? $search_result->category($request['c']) : Item::category($request['c']);
        }

        if(!$validatorS->fails()) {
            $search_result = $search_result ? $search_result->findSubject($request['s']) : Item::findSubject($request['s']);
        }

        if(!$validatorQ->fails()) {
            $search_result = $search_result ? $search_result->title($request['q']) : Item::title($request['q']);
        }
    }

    return view('frontend_layouts.search', [
        'search_result' => $search_result ? $search_result->paginate(12)->appends($request->except('page')) : $search_result,
        'items' => Item::orderByDesc('document_date')->limit(4)->get(),
        'categories' => ItemType::all(),
        'subjects' => Subject::all(),
        'c' => $request['c'] ? $request['c'] : 0,
        's' => $request['s'] ? $request['s'] : 0,
        'q' => $request['q'] ? $request['q'] : ""
    ]);
})->name('search');


Route::get('/book-details/{id}', function ($id) {
    // $item = Item::published()->findOrFail($id);
    // if(Auth::check() && $item->uploaded_by->id == Auth::user()->id) {
    //     // do nothing, just continue
    // } else if($item->visibility && $item->visibility->type > 1) {
    //     if(Auth::check()) {
    //         Log::info(Auth::check());
    //         Log::info($item->visibility->users);
    //         if($item->visibility->type == 3) {
    //             Log::info('type 3');
    //             $user = $item->visibility->users()->where('user_id', Auth::user()->id)->get();
    //             Log::info($user);
    //             Log::info($user->count());
    //             if($user->count() >= 1) {
    //                 Log::info('abort');
    //                 return abort(403, "You are not allowed to access this document");
    //             }
    //         }

    //         if($item->visibility->type == 4) {
    //             Log::info('type 4');
    //             $item->visibility->users()->where('user_id', Auth::user()->id)->firstOrFail();
    //         }
    //     } else {
    //         return redirect()->route('login', ['next' => URL::to('/book-details/'.$id)]);
    //     }
    // }

    $item = Item::with("visibility.users")->findOrFail($id);
    if($item->visibility->type != 1 && $item->visibility->type != 2) {
        if(Auth::check()) {
            if($item->visibility->type == 4) {
                $allowed_ids = array_map(function($user){
                    return $user["id"];
                }, $item->visibility->users->toArray());
                if(!in_array(auth()->user()->id, $allowed_ids) && $item->user_id != auth()->user()->id) {
                    return abort(403, "Sorry ".auth()->user()->first_name.", you are not allowed to access this document.");
                }
            }
        } else {
            return redirect()->route("login", ["next" => URL::to("/book-details/".$id)]);
        }
    } elseif($item->visibility->type == 2) {
        if(!Auth::check())
            return redirect()->route("login", ["next" => URL::to("/book-details/".$id)]);
    }

    return view('frontend_layouts.book_details', [
        'item' => $item,
        'items' => Item::published()->paginate(8),
        'related_items' => Item::relatedItem($item) ? Item::relatedItem($item)->paginate(2) : Item::relatedItem($item)
    ]);
})->name('book_details');

Auth::routes();

Route::get('current_user', ['uses'=> 'ItemsController@current_user']);
Route::get('profile_photo/{id}', ['uses' => 'UsersController@show_profile']);
Route::get('items/{total}/{offset}', ['uses'=> 'ItemFilesController@get_items']);

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    Route::get('users/{id}/delete', 'UsersController@delete')->name('users.delete');
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::resource('items', 'ItemsController', ['only' => ['index', 'show', 'edit', 'create']]);
    Route::get('countries/{id}/delete', 'CountriesController@delete')->name('countries.delete');
    Route::resource('countries', 'CountriesController');

    Route::get('categories/{id}/delete', 'ItemTypesController@delete')->name('categories.delete');
    Route::resource('categories', 'ItemTypesController');

    Route::get('authors/{id}/delete', 'AuthorsController@delete')->name('authors.delete');
    Route::resource('authors', 'AuthorsController');

    Route::get('subject/{id}/delete', 'SubjectsController@delete')->name('subjects.delete');
    Route::resource('subjects', 'SubjectsController');

    Route::get('profile', 'ProfileController@edit')->name('profile');
    Route::post('profile', 'ProfileController@update')->name('profile');
    Route::get('setting', 'SettingController@edit')->name('setting');
    Route::post('setting', 'SettingController@update')->name('setting');
    Route::get('notifications', 'NotificationController@index')->name('notifications');
    Route::get('trash', 'TrashController@index')->name('trash');
});

Route::redirect('/admin', '/admin/dashboard', 301);

app/Models/Subject.php
<?php

/**
 * Created by Reliese Model.
 * Date: Sun, 14 Jan 2018 21:07:40 +0700.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Subject
 * 
 * @property int $id
 * @property string $name
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 * @property \Illuminate\Database\Eloquent\Collection $items
 *
 * @package App\Models
 */
class Subject extends Eloquent
{
	protected $fillable = [
		'name'
	];

	public function items()
	{
		return $this->hasMany(\App\Models\Item::class);
	}
}

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $fillable = [
        'name'
    ];

    public function items()
    {
        return $this->hasMany('App\Item', 'subject_id', 'id');
    }
}

app/Http/Controllers/API/SubjectsController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Subject;
use App\Http\Resources\Subjects as SubjectsResource;

class SubjectsController extends Controller
{
    public function index()
    {
            return SubjectsResource::collection(Subject::all());
    }


    public function create()
    {

    }

    public function edit()
    {

    }
}

app/Http/Controllers/SubjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Subject;

class SubjectsController extends Controller
{
    public function __construct()
    {
        $this->middleware('role', ['except' => ['index']]);
    }

    public function index()
    {
        return view('subjects.index', ['subjects' => Subject::all()]);
    }


    public function create()
    {
        return view('subjects.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
        ]);

        if($validator->fails()) {
            return back()
                ->with('alert-danger', 'Form error!')
                ->withErrors($validator)
                ->withInput();
        }

        $subject = Subject::create([
            'name' => $request['name'],
        ]);

        return back()->with('alert-success', 'New subject created');
    }

    public function edit($id)
    {
        $subject = Subject::findOrFail($id);
        return view('subjects.edit', ['subject' => $subject]);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
        ]);

        if($validator->fails()) {
            return back()
                ->with('alert-danger', 'Form error!')
                ->withErrors($validator)
                ->withInput();
        }

        $subject = Subject::findOrFail($id);
        $subject->name = $request['name'];
        $subject->save();

        return back()->with('alert-success', 'Subject data saved');
    }

    public function destroy($id)
    {
        $subject = Subject::findOrFail($id);
        $subject->delete();
        return redirect()->route('subjects.index');
    }


    public function delete($id)
    {
        $subject = Subject::findOrFail($id);
        return view('subjects.delete', ['subject' => $subject]);
    }
}

resources/views/subjects/create.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Create Subject</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('subjects.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control"value="{{ old('name') }}">
                    </div>
                    <button type="submit" class="btn btn-md btn-primary pull-right">CREATE</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/subjects/delete.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Delete Subject</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('subjects.destroy', [$subject->id]) }}">
                    {{ csrf_field() }}
                    <input name="_method" type="hidden" value="DELETE">
                    <input name="id" type="hidden" value="{{$subject->id}}">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control"value="{{ old('name', $subject->name) }}" readonly>
                    </div>
                    <a href="{{route('subjects.index')}}" class="btn btn-md btn-primary pull-left">CANCEL</a>
                    <button type="submit" class="btn btn-md btn-danger pull-right">DELETE</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/subjects/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-8">
        <div class="panel panel-default">
            <div class="panel-heading">Edit Subject</div>
            <div class="panel-body">
                @if($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" class="form" action="{{ route('subjects.update', [$subject->id]) }}">
                    {{ csrf_field() }}
                    <input name="_method" type="hidden" value="PUT">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" class="form-control"value="{{ old('name', $subject->name) }}">
                    </div>
                    <button type="submit" class="btn btn-md btn-primary pull-right">SAVE</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/subjects/index.blade.php
@extends('layouts.main')

@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                Author List
                @if(Auth::user()->isAdmin() || Auth::user()->isRoot())
                <a class="btn btn-success btn-xs pull-right" href="{{route('subjects.create')}}">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Subject
                </a>
                @endif
            </div>

            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Total Items</th>
                            <th>Created at</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($subjects as $subject)
                        <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $subject->name }}</td>
                            <td>{{ $subject->items->count() }}</td>
                            <td>{{ $subject->created_at }}</td>
                            <td>
                                @if(Auth::user()->isAdmin() || Auth::user()->isRoot())
                                <a href="{{route('subjects.edit', [$subject->id])}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                <a href="{{route('subjects.delete', [$subject->id])}}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection